In [13]:
import pandas as pd
import numpy as np

In [185]:
matches = pd.read_csv("matches.csv")

matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,22/05/16,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,24/05/16,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,25/05/16,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,27/05/16,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,29/05/16,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [186]:
matches.isnull().sum()

matches.drop(columns = 'umpire3' , inplace=True )

In [187]:
teams = pd.concat([matches['team1'], matches['team2']]).unique()  # Combine team1 and team2 to get all teams
team_ids = {team: idx for idx, team in enumerate(teams)}

In [188]:
matches['team1'] = matches['team1'].map(team_ids)
matches['team2'] = matches['team2'].map(team_ids)
matches['toss_winner'] = matches['toss_winner'].map(team_ids)

In [193]:
matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,0,2017-05-04,0,4,4,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,1,2017-06-04,1,3,3,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,2,2017-07-04,2,5,5,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,3,2017-08-04,3,7,7,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
4,5,2017,4,2017-08-04,4,6,4,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,26,2016-05-22,6,4,4,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford
632,633,2016,4,2016-05-24,2,4,4,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena
633,634,2016,7,2016-05-25,0,5,5,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin
634,635,2016,7,2016-05-27,2,0,0,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan
635,636,2016,4,2016-05-29,0,4,0,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford

In [191]:
city = matches['city'].unique()
city_ids = {city:idx for idx , city  in enumerate(city)}
matches['city'] = matches['city'].map(city_ids)

In [192]:
matches['date'] = pd.to_datetime(matches['date'], format='mixed')

In [194]:
toss_result = matches['toss_decision'].unique()
toss_result_id = {toss_result:idx for idx , toss_result in enumerate(toss_result)}

toss_result_id

{'field': 0, 'bat': 1}

In [196]:
matches['toss_decision'] = matches['toss_decision1']

matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,toss_decision1
0,1,2017,0,2017-05-04,0,4,4,0,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,0
1,2,2017,1,2017-06-04,1,3,3,0,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,0
2,3,2017,2,2017-07-04,2,5,5,0,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,0
3,4,2017,3,2017-08-04,3,7,7,0,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,0
4,5,2017,4,2017-08-04,4,6,4,1,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,26,2016-05-22,6,4,4,0,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,0
632,633,2016,4,2016-05-24,2,4,4,0,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,0
633,634,2016,7,2016-05-25,0,5,5,0,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,0
634,635,2016,7,2016-05-27,2,0,0,0,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,0
635,636,2016,4,2016-05-29,0,4,0,1,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,1

In [198]:
matches['winner1'] = matches['winner'].map(team_ids)

In [200]:
matches['winner'] = matches['winner1']

In [202]:
matches.drop(columns = ['winner1'], inplace = True)

In [206]:
matches.drop(columns = ['venue' , 'umpire1' , 'umpire2' ], inplace = True)

In [208]:
matches.drop(columns = ['player_of_match' , 'result'], inplace = True)

In [215]:
matches.dropna()

,id,season,city,date,team1,team2,toss_winner,toss_decision,dl_applied,winner,win_by_runs,win_by_wickets,toss_decision1
0,1,2017,0,2017-05-04,0,4,4,0,0,0.0,35,0,0
1,2,2017,1,2017-06-04,1,3,3,0,0,3.0,0,7,0
2,3,2017,2,2017-07-04,2,5,5,0,0,5.0,0,10,0
3,4,2017,3,2017-08-04,3,7,7,0,0,7.0,0,6,0
4,5,2017,4,2017-08-04,4,6,4,1,0,4.0,15,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,26,2016-05-22,6,4,4,0,0,4.0,0,6,0
632,633,2016,4,2016-05-24,2,4,4,0,0,4.0,0,4,0
633,634,2016,7,2016-05-25,0,5,5,0,0,0.0,22,0,0
634,635,2016,7,2016-05-27,2,0,0,0,0,0.0,0,4,0
635,636,2016,4,2016-05-29,0,4,0,1,0,0.0,8,0,1

In [218]:
matches.dropna(subset=['winner'], inplace=True)

In [221]:
matches['winner'] = matches['winner'].astype('int64')

In [224]:
matches.corr()

,id,season,city,date,team1,team2,toss_winner,toss_decision,dl_applied,winner,win_by_runs,win_by_wickets,toss_decision1
id,1.000000,0.469260,0.100527,0.469885,-0.071502,-0.028329,-0.061164,-0.051925,0.024989,-0.088098,-0.008012,-0.011641,-0.051925
season,0.469260,1.000000,-0.115942,0.997486,-0.284424,-0.258361,-0.289813,-0.213946,0.004501,-0.305125,-0.015699,0.001282,-0.213946
city,0.100527,-0.115942,1.000000,-0.117044,0.110014,0.133294,0.106988,0.058544,0.023808,0.253515,0.020113,-0.058117,0.058544
date,0.469885,0.997486,-0.117044,1.000000,-0.284385,-0.258616,-0.291085,-0.214468,0.004378,-0.303358,-0.017107,0.004665,-0.214468
team1,-0.071502,-0.284424,0.110014,-0.284385,1.000000,-0.015369,0.453118,0.095654,-0.023684,0.499673,-0.047827,0.060805,0.095654
team2,-0.028329,-0.258361,0.133294,-0.258616,-0.015369,1.000000,0.539585,0.086694,0.040783,0.474343,0.032801,-0.085365,0.086694
toss_winner,-0.061164,-0.289813,0.106988,-0.291085,0.453118,0.539585,1.000000,0.080244,0.052369,0.474810,0.013445,-0.035319,0.080244
toss_decision,-0.051925,-0.213946,0.058544,-0.214468,0.095654,0.086694,0.080244,1.000000,-0.017794,0.087522,-0.021105,-0.002527,1.000000
dl_applied,0.024989,0.004501,0.023808,0.004378,-0.023684,0.040783,0.052369,-0.017794,1.000000,0.033745,-0.011338,-0.012421,-0.017794
winner,-0.088098,-0.305125,0.253515,-0.303358,0.499673,0.474343,0.474810,0.087522,0.033745,1.000000,0.001958,0.008899,0.087522
win_by_runs,-0.008012,-0.015699,0.020113,-0.017107,-0.047827,0.032801,0.013445,-0.021105,-0.011338,0.001958,1.000000,-0.569617,-0.021105
win_by_wickets,-0.011641,0.001282,-0.058117,0.004665,0.060805,-0.085365,-0.035319,-0.002527,-0.012421,0.008899,-0.569617,1.000000,-0.002527
toss_decision1,-0.051925,-0.213946,0.058544,-0.214468,0.095654,0.086694,0.080244,1.000000,-0.017794,0.087522,-0.021105,-0.002527,1.000000

In [246]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = matches.drop(columns=['id', 'season', 'date', 'toss_decision1'])

X = data.drop(columns=['winner', 'dl_applied', 'win_by_runs', 'win_by_wickets'])  # Features
y = data['winner']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier()


clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.4409448818897638